name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

name: 🚀 Deploy website on push
  jobs:
    web-deploy:
      name: 🎉 Deploy
      runs-on: ubuntu-latest
      steps:
        - name: 🚚 Get latest code
          uses: actions/checkout@v3
        
        - name: 📂 Sync files
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            ftp-host: 31.186.11.151
            ftp_username: ${{ secrets.FTP_USERNAME }}
            ftp_password: ${{ secrets.FTP_PASSWORD }}

       
