name: deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-lastest
    steps:
      - name: Send file to ftp
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
        with:
            ftp-host: 31.186.11.151
            ftp_username: ${{ secrets.ftp_username }}
            ftp_password: ${{ secrets.ftp_password }}

       
